### ISSUE TITLE
Slack crashes with any empty message sent

### ISSUE THREAD

**Issue by drkno** [concierge/slack#1]
```
slack-> Failed to send message, error: no_text
"slack" threw up. <unknown> is now covered in sick.
TypeError: message.callback is not a function
    at Request._callback (/home/osmc/Concierge/modules/slack/slack.js:38:25)
    at Request.self.callback (/home/osmc/Concierge/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/osmc/Concierge/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/osmc/Concierge/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

@Awarua- @fallaciousreasoning 
Descriptions in `api.sendImage` fallback to sending a message. This message could be empty if the descriptions are. The bigger problem is why the callback doesn't exist. A workaround was implemented in https://github.com/concierge/slack/commit/9ea695f7ae793a6145af87109a11421f7afdd871.

**Comment by fallaciousreasoning** [comment]
Closed fixed? Or wontfix?

**Comment by Awarua-** [comment]
Wait, I don't remember closing this, might have been by mistake sorry.
